filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/security.log
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "security-logs-%{+yyyy.MM.dd}"

setup.ilm.enabled: false
setup.template.name: "security-logs"
setup.template.pattern: "security-logs-*"
