input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => { 
      "message" => "%{IP:ip} - - \[%{HTTPDATE:timestamp}\] \"%{WORD:method} %{URIPATHPARAM:endpoint} HTTP/%{NUMBER}\" %{NUMBER:status:int} %{NUMBER:latency_ms:int}"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "security-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
